name: Test
on: pull_request
jobs:
  phpcs:
    name: PHP Code Sniffer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          php-version: '7.1'
      - uses: chekalsky/phpcs-action@v1
        with:
          enable_warnings: true
